api/urls.py
from rest_framework.routers import DefaultRouter

from api.views import RecipeViewSet


router = DefaultRouter()
router.register(r'recipes', RecipeViewSet, basename="recipe")
urlpatterns = router.urls

frontend/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from django.contrib.auth.views import LoginView, LogoutView

from frontend.views import RecipeListView, RecipeDetailView, RegisterUserView, RecipeCreateView

app_name = 'frontend'
urlpatterns = [
    path('', RedirectView.as_view(pattern_name="frontend:list-recipes"), name="home"),
    path('recipes/', RecipeListView.as_view(), name="list-recipes"),
    path('recipes/<int:pk>', RecipeDetailView.as_view(), name='recipe-detail'),
    path('recipes/add/', RecipeCreateView.as_view(), name='recipe-create'),
    path('register', RegisterUserView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

recipe_giraffe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

MEDIA_FILE_PATHS = static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('frontend.urls'))
] + MEDIA_FILE_PATHS

api/models.py
from uuid import uuid4
from django.db import models
from django.contrib.auth import get_user_model


def recipe_image_path(instance, filename):
    return '{}/{}'.format(instance.recipe_id, uuid4())


class Recipe(models.Model):
    title = models.CharField(max_length=140)
    description = models.TextField()
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return "{} by {}".format(self.title, self.user.username)


class RecipeImage(models.Model):
    image = models.ImageField(upload_to=recipe_image_path)
    uploaded = models.DateTimeField(auto_now_add=True)
    recipe = models.ForeignKey('Recipe', on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

frontend/models.py
from django.db import models

# Create your models here.

frontend/forms.py
from django import forms

from api.models import Recipe


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'description', 'user']
        widgets = {'user': forms.HiddenInput()}

api/views.py
from django.shortcuts import render
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated

from api.serializers import RecipeSerializer
from api.models import Recipe

class RecipeViewSet(viewsets.ModelViewSet):
    serializer_class = RecipeSerializer
    queryset = Recipe.objects.all()
    permission_classes = (IsAuthenticated, )

frontend/views.py
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from api.models import Recipe
from frontend.forms import RecipeForm


class RecipeListView(ListView):
    model = Recipe
    template_name = "frontend/recipe_list.html"


class RecipeDetailView(DetailView):
    model = Recipe
    template_name = "frontend/recipe_detail.html"


class RecipeCreateView(LoginRequiredMixin, CreateView):
    form_class = RecipeForm
    success_url = reverse_lazy('frontend:list-recipes')
    template_name = "frontend/recipe_create.html"

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        return initial


class RegisterUserView(CreateView):
    template_name = 'frontend/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('frontend:list-recipes')

frontend/templates/frontend/recipe_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <h1>Add Recipe</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Add</button>
    </form>
{% endblock %}

frontend/templates/frontend/recipe_detail.html
{% extends 'base.html' %}

{% block body %}
    <div>
        {% for item in object.recipeimage_set.all %}
            <img height="300" width="500" src="{{ item.image.url }}">
        {% endfor %}
        <h3>{{ object.title }}</h3>
        <span>Posted by {{ object.user }}</span>
        <p>{{ object.description }}</p>
    </div>
{% endblock %}

frontend/templates/frontend/recipe_list.html
{% extends 'base.html' %}

{% block body %}
{% for recipe in object_list %}
    <div>
        <h3><a href="{% url 'frontend:recipe-detail' pk=recipe.id %}">{{ recipe.title }}</a></h3>
        <span>Posted by {{ recipe.user }}</span>
        <p>{{ recipe.description }}</p>
    </div>
{% endfor %}
{% endblock %}

frontend/templates/frontend/register.html
{% extends 'base.html' %}

{% block body %}
<h1>Register for MyMDB</h1>
<form method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Register</button>
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <title>{% block title %}Recipe Giraffe{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">RecipeGiraffe</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'frontend:list-recipes' %}">Recipes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Top Recipes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'frontend:recipe-create' %}">Add Recipe</a>
            </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
            {% if user.is_authenticated %}
                <a class="btn btn-info ml-2" href="{% url 'frontend:logout' %}">Logout</a>
            {% else %}
                <a class="btn btn-info ml-2" href="{% url 'frontend:login' %}">Login</a>
                <a class="btn btn-info ml-2" href="{% url 'frontend:register' %}">Register</a>
            {% endif %}
        </div>
        </nav>
        <div class="container mt-2">
            {% block body %}{% endblock %}
        </div>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/jquery.min.js' %}"></script>
    </body>
</html>